### ISSUE TITLE
RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by alan-wr** [kevva/decompress#84]
rejected promise not handled within 1 second: RangeError: Array buffer allocation failed
extensionHostProcess.js:1059
stack trace: RangeError: Array buffer allocation failed
	at new ArrayBuffer (<anonymous>)
	at new Uint8Array (<anonymous>)
	at new FastBuffer (internal/buffer.js:940:1)
	at Function.alloc (buffer.js:350:10)
	at new Buffer (buffer.js:263:19)
	at Stream.writeByte (/buildarea/ashi/dev/git/gitlab_20201109/devcode/node_modules/seek-bzip/lib/index.js:479:23)
	at Bunzip._read_bunzip (/buildarea/ashi/dev/git/gitlab_20201109/devcode/node_modules/seek-bzip/lib/index.js:435:25)
	at Function.decode (/buildarea/ashi/dev/git/gitlab_20201109/devcode/node_modules/seek-bzip/lib/index.js:513:10)
	at /buildarea/ashi/dev/git/gitlab_20201109/devcode/node_modules/decompress-tarbz2/index.js:18:35
	at /buildarea/ashi/dev/git/gitlab_20201109/devcode/node_modules/decompress/index.js:19:43
	at Array.map (<anonymous>)
	at runPlugins (/buildarea/ashi/dev/git/gitlab_20201109/devcode/node_modules/decompress/index.js:19:34)
	at extractFile (/buildarea/ashi/dev/git/gitlab_20201109/devcode/node_modules/decompress/index.js:54:46)
	at /buildarea/ashi/dev/git/gitlab_20201109/devcode/node_modules/decompress/index.js:150:26

**Comment by alan-wr** [comment]
The original file *tar.bz2 is about 900+M, and after decompress it will get 3.5G.

It is fine by decompress it by tar:
command line 'tar -jxvf *.tar.bz2_4 -C output'
